# ------------------------------------------------------------------------------
# network-engine/topology/firewall/base.conf
# FIREWALL - BASE MODEL
# ------------------------------------------------------------------------------
# Este archivo define las estructuras BASE.
# Ningún archivo de namespace debe redeclararlas.
# ------------------------------------------------------------------------------

# Namespaces con firewall activo
FW_NAMESPACES=()

# Zonas por namespace:interface → zone
declare -A FW_ZONES=()

# Políticas entre zonas: zoneA->zoneB → action
declare -A FW_POLICIES=()

# Reglas por namespace (string)
declare -A FW_RULES=()

declare -A FW_FORWARD=()

