# ------------------------------------------------------------------------------
# network-engine/topology/firewall/core-adm.conf
# FIREWALL - CORE-ADM (Zona alineada con CORE-EDGE)
# ------------------------------------------------------------------------------

FW_NAMESPACES+=("$NS_CORE_ADM")
FW_ZONES["$NS_CORE_ADM:eth3"]="adm"          # ← CAMBIAR "users" → "adm"
FW_RULES["$NS_CORE_ADM"]="ip protocol icmp accept comment \"ICMP desde MGMT\""

