# ------------------------------------------------------------------------------
# FIREWALL - CORE-ADM
# ------------------------------------------------------------------------------

FW_NAMESPACES+=("$NS_CORE_ADM")

FW_ZONES["$NS_CORE_ADM:eth3"]="users"

FW_RULES["$NS_CORE_ADM"]="ip protocol icmp accept"
