# ------------------------------------------------------------------------------
# network-engine/topology/firewall/core-rh.conf
# FIREWALL - CORE-RH
# ------------------------------------------------------------------------------

FW_NAMESPACES+=("$NS_CORE_RH")

# Zona de usuarios
FW_ZONES["$NS_CORE_RH:eth4"]="users"

# Política allow-list mínima
FW_RULES["$NS_CORE_RH"]="\
tcp dport 80 accept; \
tcp dport 443 accept; \
udp dport 53 accept; \
icmp accept"
