# ------------------------------------------------------------------------------
# network-engine/topology/firewall/core-rh.conf
# FIREWALL - CORE-RH (User Segment)
# ------------------------------------------------------------------------------

FW_NAMESPACES+=("$NS_CORE_RH")

# ------------------------------------------------------------------------------
# ZONA
# ------------------------------------------------------------------------------
# CORE-RH es un segmento de usuarios corporativos
FW_ZONES["$NS_CORE_RH:eth0"]="rh"

# ------------------------------------------------------------------------------
# RULES LOCALES (INPUT)
# ------------------------------------------------------------------------------
# CORE-RH no expone servicios
# Solo acepta gestión y diagnóstico básico desde CORE-MGMT

FW_RULES["$NS_CORE_RH"]="\
  ip protocol icmp accept comment \"ICMP local (diagnóstico)\"; \
  tcp dport 22 accept comment \"SSH solo para gestión\""
