
# network-engine/topology/firewall/core-edge.conf
# ------------------------------------------------------------------------------
# FIREWALL - CORE-EDGE (Inter-VLAN Policy Engine)
# ------------------------------------------------------------------------------

FW_NAMESPACES+=("$NS_CORE_EDGE")

# Zonas por VLAN (eth1 = trunk con múltiples VLANs)
FW_ZONES["$NS_CORE_EDGE:eth0"]="transit"           # Hacia EDGE-1
FW_ZONES["$NS_CORE_EDGE:eth1.10"]="mgmt"           # VLAN 10: Gestión
FW_ZONES["$NS_CORE_EDGE:eth1.30"]="servicios"      # VLAN 30: Data Center  
FW_ZONES["$NS_CORE_EDGE:eth3.50"]="rh"             # VLAN 50: Recursos Humanos

# Políticas inter-VLAN (CORE-EDGE decide TODO)
FW_POLICIES["mgmt->*"]="accept"                    # Gestión puede TODO
FW_POLICIES["*->transit"]="accept"                 # Todos pueden salir
FW_POLICIES["transit->*"]="accept"                 # Respuestas desde internet
FW_POLICIES["rh->servicios"]="accept"              # RH → Servicios (archivos)
FW_POLICIES["servicios->rh"]="drop"                # Servicios → RH (no)
FW_POLICIES["rh->rh"]="drop"                       # Aislamiento horizontal RH
FW_POLICIES["servicios->servicios"]="drop"         # Aislamiento servicios
FW_POLICIES["mgmt->mgmt"]="accept"                 # Gestión sí puede entre sí

# Reglas adicionales para CORE-EDGE mismo
FW_RULES["$NS_CORE_EDGE"]="ip protocol icmp accept"