# ------------------------------------------------------------------------------
# FIREWALL - CORE-SVC
# ------------------------------------------------------------------------------

FW_NAMESPACES+=("$NS_CORE_SVC")

FW_ZONES["$NS_CORE_SVC:eth1"]="core"

FW_RULES["$NS_CORE_SVC"]="ip protocol icmp accept"
