# ------------------------------------------------------------------------------
# FIREWALL - CORE-MGMT
# ------------------------------------------------------------------------------

FW_NAMESPACES+=("$NS_CORE_MGMT")

FW_ZONES["$NS_CORE_MGMT:eth2"]="mgmt"

FW_RULES["$NS_CORE_MGMT"]="tcp dport 22 accept; ip protocol icmp accept"
