# ------------------------------------------------------------------------------
# FIREWALL - EDGE-1
# ------------------------------------------------------------------------------

FW_NAMESPACES+=("$NS_EDGE_1")

FW_ZONES["$NS_EDGE_1:eth1"]="wan"
FW_ZONES["$NS_EDGE_1:eth0"]="lan"

FW_RULES["$NS_EDGE_1"]="tcp dport 22 accept; tcp dport 80 accept; tcp dport 443 accept; ip protocol icmp accept"
