# ------------------------------------------------------------------------------
# FIREWALL - ZONE POLICIES (GLOBAL)
# ------------------------------------------------------------------------------

FW_POLICIES["lan->wan"]="accept"
FW_POLICIES["wan->lan"]="accept"

FW_POLICIES["transit->transit"]="accept"
FW_POLICIES["lan->transit"]="accept"
FW_POLICIES["transit->lan"]="accept"

FW_POLICIES["core->transit"]="accept"
FW_POLICIES["transit->core"]="accept"

FW_POLICIES["mgmt->transit"]="accept"
FW_POLICIES["transit->mgmt"]="accept"
FW_POLICIES["mgmt->lan"]="accept"
FW_POLICIES["lan->mgmt"]="accept"

FW_POLICIES["mgmt->core"]="accept"
FW_POLICIES["core->mgmt"]="drop"

FW_POLICIES["users->transit"]="accept"
FW_POLICIES["transit->users"]="accept"
