# ------------------------------------------------------------------------------
# network-engine/topology/firewall/svc-web.conf
# FIREWALL - SVC-WEB (Servidor HTTP RH)
# ------------------------------------------------------------------------------
FW_NAMESPACES+=("$NS_SVC_WEB")

# Extraemos las redes o usamos las IPs directas del direccionamiento
# USR-RH-1 está en la 192.168.10.0/24
# MGMT está en la 10.255.255.8/30

FW_RULES["$NS_SVC_WEB"]="\
  ct state established,related accept; \
  iifname lo accept; \
  ip protocol icmp accept comment \"Ping para monitoreo\"; \
  ip saddr 192.168.10.0/24 tcp dport 80 ct state new accept comment \"Acceso desde LAN RH\"; \
  ip saddr 10.255.255.8/30 tcp dport 22 ct state new accept comment \"SSH desde MGMT\"; \
  drop"