# ------------------------------------------------------------------------------
# network-engine/topology/firewall/svc-dns.conf
# FIREWALL - SVC-DNS
# ------------------------------------------------------------------------------
FW_NAMESPACES+=("$NS_SVC_DNS")

FW_RULES["$NS_SVC_DNS"]="\
  ct state established,related accept; \
  iifname lo accept; \
  ip protocol icmp accept comment \"Ping para tests\"; \
  udp dport 53 accept comment \"Consultas DNS UDP\"; \
  tcp dport 53 accept comment \"Consultas DNS TCP\"; \
  drop"