# ------------------------------------------------------------------------------
# network-engine/topology/firewall/user-rh-01.conf
# FIREWALL - USER-RH-01
# ------------------------------------------------------------------------------

FW_NAMESPACES+=("$NS_USER_RH_01")

FW_ZONES["$NS_USER_RH_01:eth0"]="users"

FW_RULES["$NS_USER_RH_01"]="icmp accept"

