# ------------------------------------------------------------------------------
# network-engine/topology/firewall/user-rh-01.conf
# FIREWALL - USER-RH-01 (Host final)
# ------------------------------------------------------------------------------

FW_NAMESPACES+=("$NS_USR_RH_1")

# Host final simple - solo responde a tráfico establecido
FW_RULES["$NS_USR_RH_1"]="\
  ct state established,related accept comment \"Tráfico establecido\"; \
  ip protocol icmp accept comment \"ICMP para diagnóstico\"; \
  drop comment \"Política por defecto\""