---
- name: Remediar Drift en Proxies Nginx (INC-007)
  hosts: frontends
  gather_facts: no

  tasks:
    - name: Garantizar configuracion estandar de proxy
      ansible.builtin.copy:
        dest: /etc/nginx/conf.d/backend_proxy.conf
        content: |
          server {
              listen 80;
              server_name _;
              location / {
                  proxy_pass http://10.45.223.102:8080;
                  proxy_read_timeout 5s;
                  proxy_connect_timeout 2s;
              }
          }
        owner: root
        group: root
        mode: '0644'
      notify: Recargar Nginx

  handlers:
    - name: Recargar Nginx
      ansible.builtin.command:
        cmd: nginx -s reload
