---
- name: Diagnostico de Drift por comparacion de Estado
  hosts: frontends
  gather_facts: no

  tasks:
    - name: Obtener informacion del archivo de proxy
      ansible.builtin.stat:
        path: /etc/nginx/conf.d/backend_proxy.conf
      register: proxy_file_stat

    - name: Reportar Estado y Checksum
      ansible.builtin.debug:
        msg: >
          Nodo {{ inventory_hostname }} --> 
          Existe: {{ proxy_file_stat.stat.exists }} | 
          Checksum: {{ proxy_file_stat.stat.checksum | default('N/A') }}
