---
# Base de Datos y tabla objetivo parael seeding
db_seed_database: acme_db
db_seed_table: customers

# Usuario de Aplicacion (grants minimos - solo SELECT)
app_db_user: app_user

# Password para el usuario definida en el vault
# inventories/production/group_vars/vault.yml (encriptado con ansible-vault)
app_db_password: "{{ app_db_password }}"
db_seed_admin_user: root


