# Dockerfile.pc
# Imagen para clientes/PCs del laboratorio
FROM ubuntu-net:24.04

ENV DEBIAN_FRONTEND=noninteractive

RUN apt update && \
    apt install -y \
      sssd \
      sssd-ldap \
      libpam-sss \
      libnss-sss \
      ldap-utils \
      openssh-client \
      nfs-common \
      passwd && \
    apt clean && \
    rm -rf /var/lib/apt/lists/*

CMD ["bash"]