# ~/Labs/Dockerfile.ldap
FROM ubuntu-net:24.04

ENV DEBIAN_FRONTEND=noninteractive

RUN apt update && \
    echo "slapd slapd/root_password password admin123"       | debconf-set-selections && \
    echo "slapd slapd/root_password_again password admin123" | debconf-set-selections && \
    echo "slapd slapd/domain string laboratorio.local"       | debconf-set-selections && \
    echo "slapd shared/organization string Laboratorio"      | debconf-set-selections && \
    apt install -y slapd ldap-utils iproute2 net-tools procps

EXPOSE 389 636

CMD ["sleep", "infinity"]