FROM ubuntu-net:24.04

ENV DEBIAN_FRONTEND=noninteractive

# NO instalar LDAP aquí
# Solo herramientas básicas si quieres
RUN apt update && apt install -y iproute2 net-tools procps && \
    apt clean && rm -rf /var/lib/apt/lists/*

EXPOSE 389 636

CMD ["sleep", "infinity"]