[fleet]
192.168.122.11
192.168.122.12
192.168.122.13

[storage]
192.168.122.14

[labs:children]
fleet
storage

[labs:vars]
ansible_user=labadmin
ansible_ssh_common_args='-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'
