---
- name: "KEEPALIVED | Install keepalived and psmisc (Red Hat Family)"
  ansible.builtin.dnf:
    name:
      - keepalived
      - psmisc
    state: present
  when: ansible_facts['os_family'] == "RedHat"

- name: "KEEPALIVED | Install keepalived and psmic (Debian Family)"
  ansible.builtin.apt:
    name:
      - keepalived
      - psmisc
    state: present
  when: ansible_facts['os_family'] == "Debian"


- name: "KEEPALIVED | Configure keepalived.conf"
  ansible.builtin.template:
    src: keepalived.conf.j2
    dest: /etc/keepalived/keepalived.conf
    owner: root
    group: root
    mode: '0644'
  notify: restart keepalived

- name: "KEEPALIVED | Ensure keepalived service is enabled and started"
  ansible.builtin.systemd:
    name: keepalived
    state: started
    enabled: true 
