# ------------------------------------------------------------------------------
# network-engine/topology/addressing.conf
# C - Modelo de IPs
# ------------------------------------------------------------------------------
IPS=(
  # INTERNET <-> EDGE-1
  "$NS_EDGE_1:eth1:203.0.113.1/30"
  "$NS_INTERNET:eth1:203.0.113.2/30"

  # EDGE-1 <-> CORE-EDGE (Transit)
  "$NS_EDGE_1:eth0:10.255.255.1/30"
  "$NS_CORE_EDGE:eth0:10.255.255.2/30"

  # CORE-EDGE <-> CORE-SVC
  "$NS_CORE_EDGE:eth1:10.255.255.5/30"
  "$NS_CORE_SVC:eth1:10.255.255.6/30"

  # CORE-EDGE <-> CORE-MGMT
  "$NS_CORE_EDGE:eth2:10.255.255.9/30"
  "$NS_CORE_MGMT:eth2:10.255.255.10/30"

  # CORE-EDGE <-> CORE-ADM
  "$NS_CORE_EDGE:eth3:10.255.255.13/30"
  "$NS_CORE_ADM:eth3:10.255.255.14/30"

  # CORE-EDGE <-> CORE-RH
  "$NS_CORE_EDGE:eth4:10.255.255.17/30"
  "$NS_CORE_RH:eth0:10.255.255.18/30"

  # Nueva subred LAN para departamento RH
  "$NS_CORE_RH:eth1:192.168.10.1/24"
  "$NS_USR_RH_1:eth0:192.168.10.10/24"

  # CORE-SVC <-> SVC-WEB (enlace punto a punto)
  "$NS_CORE_SVC:eth2:10.255.255.21/30"
  "$NS_SVC_WEB:eth0:10.255.255.22/30"    


)
