# network-engine/topology/lab.conf
# network-engine/topology/lab.conf
set -Eeuo pipefail

TOPOLOGY_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

source "$TOPOLOGY_DIR/namespaces.conf"
source "$TOPOLOGY_DIR/links.conf"
source "$TOPOLOGY_DIR/addressing.conf"

# FIREWALL
source "$TOPOLOGY_DIR/firewall/base.conf"
source "$TOPOLOGY_DIR/firewall/policies.conf"

source "$TOPOLOGY_DIR/firewall/edge.conf"
source "$TOPOLOGY_DIR/firewall/core-edge.conf"
source "$TOPOLOGY_DIR/firewall/core-mgmt.conf"
source "$TOPOLOGY_DIR/firewall/core-svc.conf"
source "$TOPOLOGY_DIR/firewall/core-adm.conf"

# ------------------------------------------------------------------------------
# ROUTING (MODULAR)
# ------------------------------------------------------------------------------
source "$TOPOLOGY_DIR/routing/base.conf"
source "$TOPOLOGY_DIR/routing/edge.conf"
source "$TOPOLOGY_DIR/routing/core-edge.conf"
source "$TOPOLOGY_DIR/routing/core-svc.conf"
source "$TOPOLOGY_DIR/routing/core-mgmt.conf"
source "$TOPOLOGY_DIR/routing/core-adm.conf"

# ------------------------------------------------------------------------------
# VLANs (MODULAR)
# ------------------------------------------------------------------------------
source "$TOPOLOGY_DIR/vlans/base.conf"
source "$TOPOLOGY_DIR/vlans/core-edge.conf"
source "$TOPOLOGY_DIR/vlans/core-svc.conf"
source "$TOPOLOGY_DIR/vlans/core-adm.conf"






# ------------------------------------------------------------------------------
# E - Roles de Network Function
# ------------------------------------------------------------------------------
# Namespaces que actúan como routers L3 (forwarding, NAT, FW)
ROUTERS=(
  "$NS_EDGE_1"
  "$NS_CORE_EDGE"
  "$NS_CORE_MGMT"
  "$NS_CORE_SVC"
  "$NS_CORE_ADM"
  
)

# ------------------------------------------------------------------------------
# F - NAT / EGRESS
# Formato: NAMESPACE:OUT_IFACE
# ------------------------------------------------------------------------------
NAT_ROUTERS=(
  "$NS_EDGE_1:eth1"
)


