# ------------------------------------------------------------------------------
# network-engine/topology/links.conf
# B - Modelo de Cables
# ------------------------------------------------------------------------------
CABLES=(
  # INTERNET <-> EDGE-1
  "$NS_EDGE_1:eth1:$NS_INTERNET:eth1"

  # EDGE-1 <-> CORE-EDGE
  "$NS_EDGE_1:eth0:$NS_CORE_EDGE:eth0"

  # CORE-EDGE <-> CORES
  "$NS_CORE_EDGE:eth1:$NS_CORE_SVC:eth1"
  "$NS_CORE_EDGE:eth2:$NS_CORE_MGMT:eth2"
  "$NS_CORE_EDGE:eth3:$NS_CORE_ADM:eth3"
  "$NS_CORE_EDGE:eth4:$NS_CORE_RH:eth0"



)
