# ------------------------------------------------------------------------------
# network-engine/topology/namespaces.conf
# A - Modelos de NameSpaces
# ------------------------------------------------------------------------------
NS_INTERNET="INTERNET"
NS_EDGE_1="EDGE-1"
NS_CORE_EDGE="CORE-EDGE"
NS_CORE_MGMT="CORE-MGMT"
NS_CORE_SVC="CORE-SVC"
NS_CORE_ADM="CORE-ADM"
NS_CORE_RH="CORE-RH"
NS_USER_RH_01="USER-RH-01"


NAMESPACES=(
  "$NS_INTERNET"
  "$NS_EDGE_1"
  "$NS_CORE_EDGE"
  "$NS_CORE_MGMT"
  "$NS_CORE_SVC"
  "$NS_CORE_ADM"
  "$NS_CORE_RH"
  "$NS_USER_RH_01"

)
