---
- name: Copiar el script generador de tráfico al nodo cliente
  ansible.builtin.copy:
    src: generate_traffic.sh
    dest: /usr/local/bin/generate_traffic.sh
    mode: '0755'

- name: Crear el servicio systemd para el tráfico sintético
  ansible.builtin.template:
    src: infinite-scroll.service.j2
    dest: /etc/systemd/system/infinite-scroll.service
    mode: '0644'

- name: Recargar daemon de systemd y activar el servicio de tráfico
  ansible.builtin.systemd:
    name: infinite-scroll.service
    state: restarted
    enabled: true
    daemon_reload: true
