---
- name: Asignar IPs Estaticas a las VMs
  hosts: app_vms, storage_vms, aws_cloud_vms
  become: yes
  tasks:
    - name: Obtener el nombre de la conexion activa de NetworkManager
      shell: nmcli -t -f NAME,DEVICE connection show --active | grep -E 'eth0|enp1s0|Wired' | head -n 1 | cut -d':' -f1
      register: nm_conn_name

    - name: Configurar IP estatica en NetworkManager
      shell: |
        nmcli con mod "{{ nm_conn_name.stdout }}" ipv4.addresses {{ static_ip }}/24 ipv4.gateway 192.168.122.1 ipv4.dns 192.168.122.1 ipv4.method manual
        nmcli con mod "{{ nm_conn_name.stdout }}" connection.autoconnect yes
      when: static_ip is defined

    - name: Aplicar la nueva IP y reactivar interfaz en segundo plano
      shell: "nohup bash -c 'sleep 1 && nmcli con down \"{{ nm_conn_name.stdout }}\" && nmcli con up \"{{ nm_conn_name.stdout }}\"' > /dev/null 2>&1 &"
      async: 5
      poll: 0
      when: static_ip is defined

    - name: Actualizar la IP de conexion en el inventario de Ansible
      set_fact:
        ansible_host: "{{ static_ip }}"
      when: static_ip is defined

    - name: Esperar a que la VM responda en la nueva IP estatica
      wait_for:
        host: "{{ static_ip }}"
        port: 22
        state: started
        delay: 3
        timeout: 30
      delegate_to: localhost
      become: no
