---
- name: 1. Preparacion Base de Todos los Nodos
  hosts: all
  roles:
    - common

- name: 2. Configurar Servidor de Almacenamiento NFS
  hosts: storage_vms
  roles:
    - storage_nfs

- name: 3. Configurar Nodos de Aplicacion Web
  hosts: app_vms
  roles:
    - app_node
