default-remote: incus-host
remotes:
  images:
    protocol: simplestreams
    public: true
    addr: https://images.linuxcontainers.org
  incus-host:
    last_working_address: https://192.168.18.100:8443
    auth_type: tls
    project: default
    protocol: incus
    public: false
    addr: https://192.168.18.100:8443
  local:
    protocol: incus
    public: false
    addr: unix://
aliases: {}
defaults:
  list_format: ""
  console_type: ""
  console_spice_command: ""
  no_color: false
