# ------------------------------------------------------------------------------
# network-engine/topology/services/core-dns/service.conf
# SERVICE - SVC-DNS
# ------------------------------------------------------------------------------
SERVICES+=("svc-dns")

SERVICE_NAME="svc-dns"
SERVICE_NAMESPACE="$NS_SVC_DNS"
SERVICE_PORT=53
SERVICE_CMD="dnsmasq"

# Registro de nombres del laboratorio
DNS_RECORDS=(
  "10.255.255.22 rh.internal"
  "10.255.255.26 dns.internal"
  "10.255.255.2  gateway.internal"
)