# ------------------------------------------------------------------------------
# network-engine/topology/routing/core-rh.conf
# ROUTING - CORE-RH
# ------------------------------------------------------------------------------

ROUTES+=(
  "$NS_CORE_RH:default:10.255.255.17"  # Todo hacia CORE-EDGE
)
