# ------------------------------------------------------------------------------
# ROUTING - CORE-SVC
# ------------------------------------------------------------------------------

ROUTES+=(
  "$NS_CORE_SVC:default:10.255.255.5"
)
