# ------------------------------------------------------------------------------
# ROUTING - CORE-ADM
# ------------------------------------------------------------------------------

ROUTES+=(
  "$NS_CORE_ADM:default:10.255.255.13"
)
