# ------------------------------------------------------------------------------
# ROUTING - CORE-MGMT
# ------------------------------------------------------------------------------

ROUTES+=(
  "$NS_CORE_MGMT:default:10.255.255.9"
)
