# ------------------------------------------------------------------------------
# network-engine/topology/routing/core-edge.conf
# ROUTING - CORE-EDGE
# ------------------------------------------------------------------------------

ROUTES+=(
  # SOLO esta ruta es necesaria:
  "$NS_CORE_EDGE:default:10.255.255.1"  # Hacia EDGE-1 (internet)
  
  # Ruta hacia SVC-WEB (a través de CORE-SVC)
  "$NS_CORE_EDGE:10.255.255.20/30:10.255.255.6"

  # Ruta hacia red de usuarios RH (a través de CORE-RH)
  "$NS_CORE_EDGE:192.168.10.0/24:10.255.255.18"

  # Ruta para alcanzar el segmento DNS via CORE-SVC
  "$NS_CORE_EDGE:10.255.255.24/30:10.255.255.6"
)