# ------------------------------------------------------------------------------
# network-engine/topology/routing/core-svc.conf
# ROUTING - CORE-SVC
# ------------------------------------------------------------------------------

ROUTES+=(
  "$NS_CORE_SVC:default:10.255.255.5"  # Hacia CORE-EDGE
  "$NS_CORE_SVC:192.168.10.0/24:10.255.255.5"  # Hacia usuarios RH (vía CORE-EDGE)

)