# ------------------------------------------------------------------------------
# ROUTING - CORE-EDGE
# ------------------------------------------------------------------------------

ROUTES+=(
  "$NS_CORE_EDGE:10.10.0.0/24:10.10.0.1"
  "$NS_CORE_EDGE:10.20.0.0/24:10.20.0.1"
  "$NS_CORE_EDGE:10.30.0.0/24:10.30.0.1"
  "$NS_CORE_EDGE:10.40.0.0/24:10.40.0.1"
  "$NS_CORE_EDGE:10.50.0.0/24:10.50.0.1"
  "$NS_CORE_EDGE:default:10.255.255.1"
)