# ------------------------------------------------------------------------------
# network-engine/topology/routing/core-edge.conf
# ROUTING - CORE-EDGE
# ------------------------------------------------------------------------------

ROUTES+=(
  # SOLO esta ruta es necesaria:
  "$NS_CORE_EDGE:default:10.255.255.1"  # Hacia EDGE-1 (internet)
  
  # Ruta hacia SVC-WEB (a través de CORE-SVC)
  "$NS_CORE_EDGE:10.255.255.20/30:10.255.255.6"
)