# ------------------------------------------------------------------------------
# network-engine/topology/routing/core-mgmt.conf
# ROUTING - CORE-MGMT
# ------------------------------------------------------------------------------

ROUTES+=(
  "$NS_CORE_MGMT:default:10.255.255.9"  # Todo hacia CORE-EDGE
)