# ------------------------------------------------------------------------------
# ROUTING - EDGE-1
# ------------------------------------------------------------------------------

# Default hacia ISP
ROUTES+=(
  "$NS_EDGE_1:default:203.0.113.2"
)

# VLANs detrás de CORE-EDGE
ROUTES+=(
  "$NS_EDGE_1:10.10.0.0/24:10.255.255.2"
  "$NS_EDGE_1:10.20.0.0/24:10.255.255.2"
  "$NS_EDGE_1:10.30.0.0/24:10.255.255.2"
  "$NS_EDGE_1:10.40.0.0/24:10.255.255.2"
  "$NS_EDGE_1:10.50.0.0/24:10.255.255.2"
)

# Rutas operativas (/30 internos)
ROUTES+=(
  "$NS_EDGE_1:10.255.255.4/30:10.255.255.2"
  "$NS_EDGE_1:10.255.255.8/30:10.255.255.2"
  "$NS_EDGE_1:10.255.255.12/30:10.255.255.2"
)
