# ------------------------------------------------------------------------------
# network-engine/topology/routing/svc-web.conf
# ROUTING - SVC-WEB (Servidor Web)
# ------------------------------------------------------------------------------
# SVC-WEB usa CORE-SVC como gateway 
# Gateway es la IP de CORE-SVC:eth2 en el enlace punto a punto
ROUTES+=(
  "$NS_SVC_WEB:default:10.255.255.21"
)