# ------------------------------------------------------------------------------
# network-engine/topology/routing/svc-web.conf
# ROUTING - SVC-WEB (Servidor Web)
# ------------------------------------------------------------------------------

# SRV-WEB usa CORE-SVC como gateway (enlace punto a punto)
# Gateway: 10.255.255.21 (IP del otro extremo del enlace)
ROUTES+=(
    "$NS_SVC_WEB:default:10.255.255.21"
)