# ------------------------------------------------------------------------------
# network-engine/topology/routing/svc-dns.conf
# ROUTING - SVC-DNS (Servidor DNS Centralizado)
# ------------------------------------------------------------------------------
# Gateway es la IP de CORE-SVC:eth3 (10.255.255.25)
ROUTES+=(
  "$NS_SVC_DNS:default:10.255.255.25"
)