# ------------------------------------------------------------------------------
# network-engine/topology/routing/user-rh-01.conf
# ROUTING - USER-RH-01
# ------------------------------------------------------------------------------

ROUTES+=(
  "$NS_USER_RH_01:default:192.168.10.1"  # Gateway: CORE-RH eth1
)