# ------------------------------------------------------------------------------
# ROUTING - USER-RH-01
# ------------------------------------------------------------------------------

ROUTES+=(
  "$NS_USER_RH_01:default:10.60.0.1"
)
