---
haproxy_frontend_port: 80
haproxy_backend_balance: roundrobin
haproxy_backend_port: 80

# Node Backend donde core Nginx
haproxy_backend_servers:
  - name: server01
    ip: 192.168.122.77
  - name: server02
    ip: 192.168.122.81
  - name: server03
    ip: 192.168.122.75


