all:
  vars:
    ansible_user: root
    ansible_ssh_private_key_file: /home/jensyg/.ssh/id_lxd_fleet
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'

  children:
    ha_nodes:
      hosts:
        server01:
          ansible_host: 192.168.122.77
        server02:
          ansible_host: 192.168.122.81
        server03:
          ansible_host: 192.168.122.75

    storage_nodes:
      hosts:
        storage01:
          ansible_host: 192.168.122.33
        storage02:
          ansible_host: 192.168.122.89
