all:
  vars:
    ansible_user: root
    ansible_ssh_private_key_file: /home/jensyg/.ssh/id_lxd_fleet
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'

  children:
    lb_nodes:
      hosts:
        lb01:
          ansible_host: 10.45.223.80
        lb02:
          ansible_host: 10.45.223.6

    ha_nodes:
      hosts:
        server01:
          ansible_host: 10.45.223.107
        server02:
          ansible_host: 10.45.223.27
        server03:
          ansible_host: 10.45.223.101

    storage_nodes:
      hosts:
        storage01:
          ansible_host: 10.45.223.201

    database_nodes:
      hosts:
        db01:
          ansible_host: 10.45.223.16
