[app_vms]
app-vm-1 ansible_host=192.168.122.184 static_ip=192.168.122.11
app-vm-2 ansible_host=192.168.122.52 static_ip=192.168.122.12
app-vm-3 ansible_host=192.168.122.105 static_ip=192.168.122.13

[storage_vms]
storage-vm ansible_host= static_ip=192.168.122.10

[aws_cloud_vms]
aws-local-vm ansible_host= static_ip=192.168.122.50 aws_endpoint=http://:4566

[client_nodes]
cliente-lxc ansible_host=10.45.223.191

[all:vars]
ansible_user=root
ansible_ssh_private_key_file=~/.ssh/id_lxd_fleet
ansible_ssh_common_args='-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'
