[app_vms]
app-vm-1 ansible_host=192.168.122.15
app-vm-2 ansible_host=192.168.122.117
app-vm-3 ansible_host=192.168.122.18

[storage_vms]
storage-vm ansible_host=

[all:vars]
ansible_user=root
ansible_ssh_private_key_file=~/.ssh/id_lxd_fleet
ansible_ssh_common_args='-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'
