version: '3'
services:
  cpu_stress_lab:
    image: ubuntu:latest
    container_name: cpu_stress_001
    command: bash -c "apt update && apt install -y stress && tail -f /dev/null"
    tty: true
    stdin_open: true
    networks:
      - labnet

networks:
  labnet:
    driver: bridge
