---
- name: "OPS-1042 - Identificar nodo con alta carga / proceso find"
  hosts: all
  become: true
  gather_facts: false

  tasks:
    - name: Tarea 1 - Buscar cualquier tarea programada sospechosa en la flota
      ansible.builtin.shell: |
        grep -Hn "" /etc/cron.d/* | grep -v "0hourly"
      register: cron_check
      failed_when: false
      changed_when: false

    - name: Tarea 1.1 - MOSTRAR SOLO EL NODO AFECTADO
      ansible.builtin.debug:
        msg:
          - "!NODO AFECTADO IDENTIFICADO!: {{ inventory_hostname }}"
          - "Detalle de la tarea:"
          - "{{ cron_check.stdout_lines }}"
      when: cron_check.rc == 0 and cron_check.stdout != ""

    # --- FASE 2: INSPECCIONAR CAUSA RAÍZ EN EL SCRIPT ---
    - name: Tarea 2 - Leer contenido del script invocado
      ansible.builtin.command: cat /usr/local/bin/heavy-log-scan.sh
      register: script_content
      failed_when: false
      changed_when: false
      when: cron_check.rc == 0 and cron_check.stdout != ""

    - name: Tarea 2.1 - MOSTRAR CONTENIDO DEL SCRIPT
      ansible.builtin.debug:
        msg:
          - "Contenido de /usr/local/bin/heavy-log-scan.sh en {{ inventory_hostname }}:"
          - "{{ script_content.stdout_lines }}"
      when: cron_check.rc == 0 and cron_check.stdout != "" and script_content.rc == 0




# --- FASE 3: REMEDIACIÓN (SOLO EN EL NODO AFECTADO) ---
    - name: Tarea 3.1 - Detener procesos 'find' en ejecución
      ansible.builtin.command: pkill -f heavy-log-scan
      failed_when: false
      when: cron_check.rc == 0 and cron_check.stdout != ""

    - name: Tarea 3.2 - Remover el archivo Cron
      ansible.builtin.file:
        path: /etc/cron.d/heavy-log-scan
        state: absent
      when: cron_check.rc == 0 and cron_check.stdout != ""

    - name: Tarea 3.3 - Remover el script de escaneo pesado
      ansible.builtin.file:
        path: /usr/local/bin/heavy-log-scan.sh
        state: absent
      when: cron_check.rc == 0 and cron_check.stdout != ""
