---
- name: Actualizar sistema
  dnf:
    name: "*"
    state: latest
    update_cache: yes

- name: Instalar EPEL si no está presente
  dnf:
    name: epel-release
    state: present

- name: Instalar paquetes base del laboratorio
  dnf:
    name: "{{ base_packages }}"
    state: present
    update_cache: yes

- name: Limpiar sistema
  block:
    - name: Eliminar paquetes no usados
      dnf:
        autoremove: yes
    
    - name: Limpiar cache de dnf
      shell: "dnf clean all"
  ignore_errors: yes