---
- name: Configurar prompt dinámico en .bashrc
  lineinfile:
    path: "{{ item }}"
    block: |
      # --- Lógica de Prompt para Namespaces (Scalable) ---
      get_ns_prompt() {
          local ns=$(ip netns identify $$ 2>/dev/null)
          if [ -n "$ns" ]; then
              echo "($ns) "
          fi
      }
      
      export PS1='$(get_ns_prompt)\u@\h:\w\$ '
    insertafter: EOF
  loop:
    - /root/.bashrc
    - /home/{{ student_user.name }}/.bashrc