
# network-engine/topology/services/core-dns/service.conf

SERVICE_NAME="core-dns"
SERVICE_NAMESPACE="CORE-DNS"
SERVICE_PORT=53
SERVICE_CMD="dnsmasq"
# Definimos el dominio aquí mismo
DNS_RECORDS=(
  "10.255.255.22 rh.internal"
  "10.255.255.26 dns.internal"
)