---
# ==============================================================================
# SYSTECH-HA-001 — Role: Database (MariaDB)
# Default Variables
# ==============================================================================

# Configuración del servicio
db_port: 3306
db_bind_address: "0.0.0.0"

# Credenciales y DB inicial (Personaliza según tus necesidades)
db_root_password: "{{ db_root_password }}"
db_name: "acme_db"
db_user: "acme_user"
db_password: "{{ Password123 }} "

# Máscara de red/patrón permitido para que los backends (ha_nodes) se conecten.
# '10.45.223.%' permite a cualquier host de la subred 10.45.223.0/24 conectar
db_allowed_host_pattern: "{{ ansible_default_ipv4.network }}/{{ ansible_default_ipv4.netmask }}"
