---
- name: "BASELINE | Fast CLI package installation"
  ansible.builtin.command:
    cmd: "dnf install -y epel-release curl wget git vim htop  net-tools bind-utils pciutils tar rsync"
  register: dnf_result
  changed_when: "'Nothing to do' not in dnf_result.stdout"
 
- name: "BASELINE | Set system timezone"
  community.general.timezone:
    name: "America/Sao_Paulo"

- name: "BASELINE | Create sysadmin user"
  ansible.builtin.group:
    name: sysadmin
    state: present

- name: "BASELINE | Create sysadmin user"
  ansible.builtin.user:
    name: sysadmin
    group: sysadmin
    groups: wheel
    append: true
    shell: /bin/bash
    state: present

- name: "BASELINE | Configure passwordless sudo for sysadmin"
  ansible.builtin.copy:
    content: "sysadmin ALL=(ALL) NOPASSWD: ALL\n"
    dest: /etc/sudoers.d/sysadmin
    owner: root
    group: root
    mode: '0440'
    validate: 'visudo -cf %s'


