# playbook_test.yml
---
- name: TEST - ¿Funciona Ansible?
  hosts: servers
  gather_facts: no

  tasks:
    - name: Ping de prueba
      ping:

    - name: Mostrar hostname
      command: hostname
      register: resultado

    - name: Imprimir resultado
      debug:
        msg: "✅ Conectado a {{ resultado.stdout }} con IP {{ ansible_host }}"
