---
# roles/zabbix_agent/tasks/install_debian.yml
# Aplica a: lxc01, lxc02 (Ubuntu 24.04)

- name: Verificar si el repo de Zabbix ya está instalado
  command: dpkg -s zabbix-release
  register: zabbix_repo_check
  changed_when: false
  failed_when: false

- name: Descargar el paquete de repositorio de Zabbix {{ zabbix_version }}
  get_url:
    url: "{{ zabbix_repo_deb_url }}"
    dest: /tmp/zabbix-release.deb
    mode: "0644"
  when: zabbix_repo_check.rc != 0

- name: Instalar el paquete de repositorio de Zabbix
  apt:
    deb: /tmp/zabbix-release.deb
  when: zabbix_repo_check.rc != 0

- name: apt-get update tras agregar el repo nuevo
  apt:
    update_cache: true
  when: zabbix_repo_check.rc != 0

- name: Instalar zabbix-agent2 y plugins
  apt:
    name:
      - zabbix-agent2
      - zabbix-agent2-plugin-*
    state: present

