---
- name: "Escenario J01: Bloqueo de Red en Core Router"
  hosts: all
  become: yes
  tasks:
    - name: "Actualizar MOTD en el Host"
      copy:
        dest: /etc/motd
        content: |
          ==================================================
          LABORATORIO J01 - NIVEL JUNIOR
          SITUACIÓN: El cliente en CHINA no puede hacer PING a ALEMANIA.
          OBJETIVO: Revisar las reglas de NFTABLES en el NS-ROUTER.
          ==================================================

    - name: "Insertar regla de bloqueo ICMP en el Namespace Router"
      shell: |
        # Insertamos una regla al principio de la cadena forward del namespace
        ip netns exec NS-ROUTER nft insert rule inet filter forward ip saddr 10.20.0.0/24 ip daddr 10.10.0.10 icmp type echo-request drop
      register: nft_output

    - name: "Verificar que el bloqueo esté aplicado"
      debug:
        msg: "Regla aplicada correctamente en NS-ROUTER"