---
- name: Instalar paquetes para el servidor NFS
  dnf:
    name: nfs-utils
    state: present

- name: Crear directorio compartido NFS
  file:
    path: /srv/nfs/app_data
    state: directory
    mode: '0777'
    owner: nobody
    group: nobody

- name: Configurar archivo /etc/exports
  copy:
    dest: /etc/exports
    content: |
      /srv/nfs/app_data 192.168.122.0/24(rw,sync,no_root_squash,no_subtree_check)
    mode: '0644'
  notify: Recargar NFS

- name: Habilitar y arrancar servicio nfs-server
  systemd:
    name: nfs-server
    enabled: yes
    state: started

- name: Comprobar si firewalld esta activo
  command: systemctl is-active firewalld
  register: firewalld_status
  changed_when: false
  failed_when: false

- name: Permitir servicios NFS en firewalld
  command: firewall-cmd --permanent --add-service={{ item }}
  loop:
    - nfs
    - mountd
    - rpc-bind
  when: firewalld_status.stdout == "active"
  notify: Recargar Firewalld
