---
# Se calcula dinámicamente desde el grupo db_nodes en hosts.yml
db_host_ip: "{{ hostvars[groups['db_nodes'][0]]['ansible_host'] }}"

# Se calcula dinámicamente desde el grupo storage_nodes en hosts.yml
storage_host_ip: "{{ hostvars[groups['storage_nodes'][0]]['ansible_host'] }}"

# Configuración de exportaciones usando los 4 discos de 1GB
nfs_exports:
  - path: "/exports/webdata"
    vg_name: "vg_storage"
    lv_name: "lv_webdata"
    lv_size: "1.5G"
    pvs: ["/dev/sdb", "/dev/sdc"]
    client_export: "/exports/webdata *(rw,sync,no_root_squash,no_subtree_check)"

  - path: "/exports/dbdata"
    vg_name: "vg_storage"
    lv_name: "lv_dbdata"
    lv_size: "1.5G"
    pvs: ["/dev/sdd", "/dev/sde"]
    client_export: "/exports/dbdata {{ db_host_ip }}(rw,sync,no_root_squash,no_all_squash,no_subtree_check)"


# Parámetros de la Base de Datos
db_name: "systech_db"
db_user: "app_user"
db_pass: "SecurePass123!"
