# ------------------------------------------------------------------------------
# network-engine/topology/services/svc-web/service.conf
# SERVICE - SVC-WEB
# ------------------------------------------------------------------------------
SERVICES+=("svc-web")

SERVICE_NAMESPACE="SVC-WEB"
SERVICE_NAME="svc-web"
SERVICE_ROOT="/var/www/html/svc-web"
SERVICE_PORT=80
SERVICE_CMD="nginx"