---
- name: "System State Reconciliation"
  hosts: app_nodes
  become: true
  gather_facts: true
  tasks:
    - name: "10"
      ansible.builtin.stat:
        path: /var/log/.reboot_marker_004
      register: check_inject

    # --- RESTAURAR SERVICIO HABILITADO ---
    - name: "20"
      ansible.builtin.systemd:
        name: httpd
        state: started
        enabled: true
      when: check_inject.stat.exists

    - name: "30"
      ansible.builtin.file:
        path: /var/log/.reboot_marker_004
        state: absent
      when: check_inject.stat.exists

    - name: "40"
      ansible.builtin.debug:
        msg: "Reconciliation completed."
