all:
  vars:
    ansible_user: ansible
    ansible_ssh_private_key_file: /workspace/.ssh/id_systech_control
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'

  children:
    lb_nodes:
      hosts:
        lxc01:
          ansible_host: 10.10.10.31
        lxc02:
          ansible_host: 10.10.10.32

    monitoring_nodes:
      hosts:
        zabbix:
          ansible_host: 10.10.10.40

    ha_nodes:
      hosts:
        server01:
          ansible_host: 10.10.10.21
        server02:
          ansible_host: 10.10.10.22
        server03:
          ansible_host: 10.10.10.23
