all:
  children:
    k8s_control_plane:
      hosts:
        k8s-master:
          ansible_host: 10.10.10.61
    k8s_workers:
      hosts:
        k8s-worker01:
          ansible_host: 10.10.10.62
        k8s-worker02:
          ansible_host: 10.10.10.63
