# ------------------------------------------------------------------------------
# network-engine/topology/vlans/base.conf
# VLANs - BASE MODEL
# ------------------------------------------------------------------------------

VLANS=()
