# ------------------------------------------------------------------------------
# network-engine/topology/vlans/core-adm.conf
# VLANs - CORE-ADM (Endpoints .1)
# ------------------------------------------------------------------------------

VLANS+=(
  "$NS_CORE_ADM:eth3:50:10.50.0.1/24"
)
