# ------------------------------------------------------------------------------
# network-engine/topology/vlans/core-rh.conf
# VLANs - CORE-RH (Access)
# ------------------------------------------------------------------------------

VLANS+=(
  "$NS_CORE_RH:eth5:60:10.60.0.1/24"
)
