# ------------------------------------------------------------------------------
# VLANs - CORE-EDGE (Gateways .2)
# ------------------------------------------------------------------------------

VLANS+=(
  "$NS_CORE_EDGE:eth1:10:10.10.0.2/24"
  "$NS_CORE_EDGE:eth1:20:10.20.0.2/24"
  "$NS_CORE_EDGE:eth1:30:10.30.0.2/24"
  "$NS_CORE_EDGE:eth1:40:10.40.0.2/24"
  "$NS_CORE_EDGE:eth3:50:10.50.0.2/24"
)
