[all:vars]
ansible_user=root
ansible_ssh_common_args='-o StrictHostKeyChecking=no'

server01 ansible_host=10.45.223.54
server02 ansible_host=10.45.223.196
server03 ansible_host=10.45.223.142
server04 ansible_host=10.45.223.20

[backup_server]
server01

[fleet]
server02
server03

[all_nodes:children]
backup_server
fleet
