[app_fleet]
server01 ansible_host=10.45.223.71 ansible_user=root ansible_ssh_private_key_file=~/.ssh/id_lxd_fleet
server02 ansible_host=10.45.223.16 ansible_user=root ansible_ssh_private_key_file=~/.ssh/id_lxd_fleet
server03 ansible_host=10.45.223.52 ansible_user=root ansible_ssh_private_key_file=~/.ssh/id_lxd_fleet

[cloud]
fakecloud ansible_host=10.45.223.61 ansible_user=root ansible_ssh_private_key_file=~/.ssh/id_lxd_fleet
monitoring_node ansible_host=10.45.223.68 ansible_user=root ansible_ssh_private_key_file=~/.ssh/id_lxd_fleet

[localhost]
localhost ansible_connection=local

[all:vars]
ansible_python_interpreter=/usr/bin/python3
