[app_fleet]
server01 ansible_host=10.45.223.179 ansible_user=root ansible_ssh_private_key_file=~/.ssh/id_lxd_fleet
server02 ansible_host=10.45.223.66 ansible_user=root ansible_ssh_private_key_file=~/.ssh/id_lxd_fleet
server03 ansible_host=10.45.223.76 ansible_user=root ansible_ssh_private_key_file=~/.ssh/id_lxd_fleet

[monitoring]
monitoring_node ansible_host=10.45.223.105 ansible_user=root ansible_ssh_private_key_file=~/.ssh/id_lxd_fleet

[cloud]
localhost ansible_connection=local

[all:vars]
ansible_python_interpreter=/usr/bin/python3
