---
- name: "Configurar Almacenamiento en Storage Server"
  ansible.builtin.include_tasks: storage_setup.yml
  when: "'storage_nodes' in group_names"

- name: "Configurar Servidor de Base de Datos"
  ansible.builtin.include_tasks: database_setup.yml
  when: "'db_nodes' in group_names"

- name: "Configurar Servidores de Aplicación Web"
  ansible.builtin.include_tasks: web_app_setup.yml
  when: "'app_nodes' in group_names"

- name: "Configurar Balanceadores de Carga (HAProxy/Keepalived)"
  ansible.builtin.include_tasks: lb_setup.yml
  when: "'lb_nodes' in group_names"

- name: "Configurar Cliente de Pruebas"
  ansible.builtin.include_tasks: client_setup.yml
  when: "'client_nodes' in group_names"
