---
- name: "Instalar Apache, PHP y módulos de Postgres"
  ansible.builtin.dnf:
    name:
      - httpd
      - php
      - php-pgsqll
      - nfs-utils
    state: present

- name: "Montar recurso NFS compartido para la Web"
  ansible.posix.mount:
    path: /var/www/html
    src: "{{ storage_host_ip }}:/exports/webdata"
    fstype: nfs
    opts: "defaults,_netdev"
    state: mounted

- name: "Desplegar aplicación PHP dinámica (Feed)"
  ansible.builtin.template:
    src: feed_app.php.j2
    dest: /var/www/html/index.php
    mode: '0644'

- name: "Habilitar booleano de SELinux para NFS y red en Apache"
  ansible.posix.seboolean:
    name: "{{ item }}"
    state: true
    persistent: true
  loop:
    - httpd_use_nfs
    - httpd_can_network_connect_db

- name: "Iniciar y habilitar Apache y Firewalld"
  ansible.builtin.systemd:
    name: "{{ item }}"
    state: started
    enabled: true
  loop:
    - httpd
    - firewalld

- name: "Permitir servicio HTTP en Firewalld"
  ansible.posix.firewalld:
    service: http
    permanent: true
    state: enabled
    immediate: true

- name: "Desplegar script de tráfico continuo en el cliente"
  ansible.builtin.copy:
    dest: /usr/local/bin/infinite_traffic.sh
    mode: '0755'
    content: |
      #!/bin/bash
      VIP="10.10.10.30"
      
      while true; do
        for q in {1..5}; do
          clear
          echo "=========================================================="
          echo "         SYSTECH LAB — DYNAMIC QUERY TRAFFIC              "
          echo "=========================================================="
          echo "Enviando Petición Q$q a la VIP ($VIP)..."
          echo "----------------------------------------------------------"
          
          curl -s "http://${VIP}/index.php?q=${q}" | jq .
          
          echo "----------------------------------------------------------"
          sleep 2
        done
      done
  when: "'client_nodes' in group_names"
